service: north-star

provider:
    name: aws
    runtime: nodejs8.10

functions:
    northstarcron:
        handler: north_star.northstarCron
        events:
            - schedule: cron(0 11 ? * 4 *)
    northstarapi:
        handler: north_star.northstarApi
        events:
            - http:
                path: northstar
                method: POST
    activitylist:
        handler: north_star.activeApi
        events:
            - http:
                path: activitylist
                method: POST
    inactivity_indicator:
        handler: north_star.inactiveApi
        events:
            - http:
                path: inactive
                method: POST
