service: north-star

provider:
    name: aws
    runtime: nodejs8.10

functions:
    northstarcron:
        handler: north_star.cron
        events:
            - schedule: cron(0 11 ? * 4 *)
    northstarapi:
        handler: north_star.api
        events:
            - http:
                path: northstar
                method: POST
    inactivity_indicator:
        handler: inactivity_indicator.start
        events:
            - http:
                path: inactive
                method: POST
