service: north-star

provider:
    name: aws
    runtime: nodejs8.10

functions:
    northstar:
        handler: north_star.start
        events:
            - schedule: cron(0 11 ? * 4 *)
    inactivity_indicator:
        handler: inactivity_indicator.start
        events:
            - http:
                path: inactive
                method: POST
